### PR TITLE
Add patch to apply cleanly against nginx 1.9.15 

### PR DESCRIPTION
**Pull request by wlonkly**

### CODE REVIEW

**Comment by wlonkly** [comment]
what is troup doing in here.

**Comment by wlonkly** [comment]
ok troup's is an empty commit so i think it's fine?

**Comment by wlonkly** [comment]
... haha, this is the wrong project. I'll close.

**Comment by msva** [comment]
Anyways, I've pretty fine building module with 1.10 even now. Does patch really needed?
// and btw, the project this repo forked from looks dead.

**Pull request merged**
